KermesseApp/Models/tbl_cat_producto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cat_producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cat_producto()
        {
            this.tbl_productos = new HashSet<tbl_productos>();
        }
    
        public int id_cat_producto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_productos> tbl_productos { get; set; }
    }
}

KermesseApp/Controllers/Tbl_cat_productoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KermesseApp.Models;
using Microsoft.Reporting.WebForms;

namespace KermesseApp.Controllers
{
    public class Tbl_cat_productoController : Controller
    {
        private KERMESSEEntities db = new KERMESSEEntities();

        // GET: Tbl_cat_producto
        public ActionResult tbl_catProducto() //Invokes List View
        {
            return View(db.tbl_cat_producto.ToList());
        }

        public ActionResult VwGuardarCatProd() //Invokes List View
        {
            return View(); //Returns New Prod Cat View
        }

        [HttpPost]
        public ActionResult GuardarCatProd(tbl_cat_producto tcp) //Method that saves new item
        {
            try
            {
                if (ModelState.IsValid)
                {
                    tbl_cat_producto tcProd = new tbl_cat_producto();
                    tcProd.nombre = tcp.nombre;
                    tcProd.descripcion = tcp.descripcion;
                    tcProd.estado = 1;
                    db.tbl_cat_producto.Add(tcProd); //Add new item
                    db.SaveChanges(); //Saves to model registry 
                }
                ModelState.Clear();
                return RedirectToAction("tbl_catProducto");
            }
            catch
            {
               return RedirectToAction("tbl_catProducto");
            }
           
        }

        public ActionResult EliminarCatProd(int id)
        {
            tbl_cat_producto tcp = new tbl_cat_producto();
            tcp = db.tbl_cat_producto.Find(id);
            db.tbl_cat_producto.Remove(tcp);

            db.SaveChanges();
            var list = db.tbl_cat_producto.ToList();

            return View("tbl_catProducto", list);
        }

        public ActionResult VerCatProd(int id)
        {
            var catProd = db.tbl_cat_producto.Where(x => x.id_cat_producto == id).First();
            return View(catProd);
        }

        public ActionResult EditarCatProd(int? id)
        {
            tbl_cat_producto tcp = db.tbl_cat_producto.Find(id);
            if (tcp == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(tcp);
            }
        }

        [HttpPost]
        public ActionResult ActualizarCatProd(tbl_cat_producto tcp)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(tcp).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("tbl_catProducto");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        
        public ActionResult FiltrarCatProd(String cadena)
        {
            if(String.IsNullOrEmpty(cadena))
            {
                var list = db.tbl_cat_producto.ToList();
                return View("tbl_catProducto", list);
            }
            else
            {
                var listaFiltrada = db.tbl_cat_producto.Where(x => x.nombre.Contains(cadena) || x.descripcion.Contains(cadena));
                return View("tbl_catProducto", listaFiltrada);
            }
        }

        public ActionResult VerRptCatProd(String tipo, String cadena)
        {
            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;

            //cadena = formCollection.GetValue("cadena").AttemptedValue;

            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "rptCatProducto.rdlc");
            rpt.ReportPath = ruta;

            var listaFiltrada = from a in db.tbl_cat_producto select a; //method to gather all db info

            if(!string.IsNullOrEmpty(cadena))
            {
                //List<tbl_productos> listaFiltrada = new List<tbl_productos>();
                listaFiltrada = listaFiltrada.Where(x => x.nombre.Contains(cadena) || x.descripcion.Contains(cadena));
            }

            ReportDataSource rd = new ReportDataSource("dsCatProducto", listaFiltrada);
            rpt.DataSources.Add(rd);
            //tipo = "PDF";
            var b = rpt.Render(tipo, null, out mt, out enc, out f, out s, out w);
            return new FileContentResult(b, mt);
        }
    }
}

KermesseApp/Views/Tbl_cat_producto/EditarCatProd.cshtml
@model KermesseApp.Models.tbl_cat_producto

@{
    ViewBag.Title = "EditarCatProd";
}

@using (Html.BeginForm("ActualizarCatProd", "Tbl_cat_producto", FormMethod.Post))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id_cat_producto)
    <div class="col-12 grid-margin stretch-card">
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="https://as2.ftcdn.net/v2/jpg/03/33/89/55/1000_F_333895571_p5TWdl4GOwLBn5NMTv8XHz9bu971vTpa.jpg" class="card-img-top" />
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <div class="card-title">
                            <h3 style="padding-top: 1rem;">Editar categoría de producto</h3>
                        </div>
                        <div class="card-description" style="padding-bottom: 1rem;">
                            Llene el siguiente formulario para modificar esta categoría de producto.
                        </div>
                        <div class="form-group">
                            <label>Nombre de la Categoría</label>
                            @Html.TextBoxFor(x => x.nombre, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label>Descripción de la Categoría</label>
                            @Html.TextAreaFor(x => x.descripcion, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                        </div>
                        <div class="row" style="padding-top:2rem;">
                            <div class="col">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-block btn-rounded btn-success">Guardar</button>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <button type="reset" class="btn btn-block btn-rounded btn-danger">Cancelar</button>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <a class="btn btn-rounded btn-block btn-inverse-info" href="@Url.Action("tbl_catProducto")"> Regresar </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

KermesseApp/Views/Tbl_cat_producto/FiltrarCatProd.cshtml
@model KermesseApp.Models.tbl_cat_producto

@{
    ViewBag.Title = "FiltrarCatProd";
}

<h2>FiltrarCatProd</h2>

<div>
    <h4>tbl_cat_producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_cat_producto }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KermesseApp/Views/Tbl_cat_producto/VerCatProd.cshtml
@model KermesseApp.Models.tbl_cat_producto

@{
    ViewBag.Title = "VerCatProd";
}

<div class="col-12 grid-margin stretch-card">
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="https://as2.ftcdn.net/v2/jpg/03/33/89/55/1000_F_333895571_p5TWdl4GOwLBn5NMTv8XHz9bu971vTpa.jpg" class="card-img-top" />
            </div>
            <div class="col-md-8">
                <div class="card-body ">
                    <div class="card-title">
                        <h3 style="padding-top: 1rem;">Detalle de la categoría de producto</h3>
                    </div>
                    <dt class="card-description">
                        @Html.DisplayNameFor(model => model.nombre)
                    </dt>

                    <dd style="font-size:20px; padding-bottom:1rem;">
                        @Html.DisplayFor(model => model.nombre)
                    </dd>

                    <dt class="card-description">
                        @Html.DisplayNameFor(model => model.descripcion)
                    </dt>

                    <dd style="font-size:20px; padding-bottom:1.5rem;">
                        @Html.DisplayFor(model => model.descripcion)
                    </dd> 
                    <div class="form-group" style="padding-top:2rem;">
                        <a class="btn btn-rounded btn-block btn-inverse-info" href="@Url.Action("tbl_catProducto")"> Regresar </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

KermesseApp/Views/Tbl_cat_producto/VwGuardarCatProd.cshtml
@model KermesseApp.Models.tbl_cat_producto

@{
    ViewBag.Title = "VwGuardarCatProd";
}

@using (Html.BeginForm("GuardarCatProd", "Tbl_cat_producto", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="https://as2.ftcdn.net/v2/jpg/03/33/89/55/1000_F_333895571_p5TWdl4GOwLBn5NMTv8XHz9bu971vTpa.jpg" class="card-img-top" />
                </div>
                <div class="col-md-8">
                    <div class="card-body ">
                        <div class="card-title">
                            <h3 style="padding-top: 1rem;">Añadir nueva categoría de productos</h3>
                        </div>
                        <div class="card-description" style="padding-bottom: 1rem;">
                            Llene el siguiente formulario para añadir una nueva categoría de producto.
                        </div>
                        <div class="form-group">
                            <label>Nombre de la Categoría</label>
                            @Html.TextBoxFor(x => x.nombre, new { @class = "form-control"})
                            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label>Descripción de la Categoría</label>
                            @Html.TextAreaFor(x => x.descripcion, new { @class = "form-control"})
                            @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                        </div>
                        <div class="row" style="padding-top:2rem;">
                            <div class="col">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-block btn-rounded btn-success">Guardar</button>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <button type="reset" class="btn btn-block btn-rounded btn-danger">Cancelar</button>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <a class="btn btn-rounded btn-block btn-inverse-info" href="@Url.Action("tbl_catProducto")"> Regresar </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

KermesseApp/Views/Tbl_cat_producto/tbl_catProducto.cshtml
@model IEnumerable<KermesseApp.Models.tbl_cat_producto>

@{
    ViewBag.Title = "tbl_catProducto";
}

@using (Html.BeginForm("FiltrarCatProd", "Tbl_cat_producto", FormMethod.Post))
{
    <h2 style="padding-bottom:2rem;">Categoría del Producto</h2>

    <div class="row justify-content-end" style="padding-bottom: 1rem;">
        <div class="col-md-auto" style="padding-right:8rem;">
            <p>
                <a href="@Url.Action("VwGuardarCatProd")"
                   class="btn btn-rounded btn-primary">
                    <ion-icon name="add-outline"></ion-icon>
                    <span>
                        <strong>Añadir Nuevo</strong>
                    </span>
                </a>
            </p>
        </div>
        <div class="col-sm-6" style="padding-right: 1.5rem;">
            <div class="input-group">
                @Html.TextBox("cadena", null, new { @class = "form-control col-sm-10", @placeholder = "Buscar", @name = "search-outline" })
                <div class="input-group-append">
                    <button type="submit" class="btn btn-rounded btn-success">
                        <ion-icon name="search" style="pointer-events:none;"></ion-icon> Buscar
                    </button>
                </div>
            </div>
        </div>
        <div class="col px-0">
            @Html.ActionLink("PDF", "VerRptCatProd", new { tipo = "PDF", cadena = Request.Form["cadena"] }, new { @class = "btn btn-rounded btn-inverse-info" })
            @Html.ActionLink("Word", "VerRptCatProd", new { tipo = "Word", cadena = Request.Form["cadena"] }, new { @class = "btn btn-rounded btn-inverse-info" })
            @Html.ActionLink("Excel", "VerRptCatProd", new { tipo = "Excel", cadena = Request.Form["cadena"] }, new { @class = "btn btn-rounded btn-inverse-info" })
        </div>
    </div>

    <table class="table table-hover table-responsive-xl">
        <thead style="background-color: #e6eaf1;">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.descripcion)
                </th>
                @*<th>
                          @Html.DisplayNameFor(model => model.estado)
                    </th>*@
                <th class="text-center">
                    @Html.Label("Acciones")
                </th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.estado)
                    </td>*@
                <td style="text-align:center">
                    <a class="btn btn-rounded btn-sm btn-warning" href="@Url.Action("EditarCatProd", new { id = item.id_cat_producto })"><ion-icon name="create-outline" style="pointer-events:none;"></ion-icon> Editar </a>
                    <a class="btn btn-rounded btn-sm btn-success" href="@Url.Action("VerCatProd", new { id = item.id_cat_producto })"><ion-icon name="document-text-outline" pointer-events: none;"></ion-icon> Detalle</a>
                    <a class="btn btn-rounded btn-sm btn-danger" href="@Url.Action("EliminarCatProd", new { id = item.id_cat_producto })"><ion-icon name="trash-outline" style="pointer-events: none;"></ion-icon> Eliminar </a>
                </td>
            </tr>
        }
    </table>
}