KermesseApp/Models/tbl_productos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_productos()
        {
            this.tbl_ingreso_com = new HashSet<tbl_ingreso_com>();
            this.tbl_listaprecio_det = new HashSet<tbl_listaprecio_det>();
        }
    
        public int id_producto { get; set; }
        public int id_comunidad { get; set; }
        public int id_cat_producto { get; set; }
        public string nombre { get; set; }
        public string desc_presentacion { get; set; }
        public int cantidad { get; set; }
        public decimal precio_venta { get; set; }
        public int estado { get; set; }
    
        public virtual tbl_cat_producto tbl_cat_producto { get; set; }
        public virtual tbl_comunidad tbl_comunidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ingreso_com> tbl_ingreso_com { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_listaprecio_det> tbl_listaprecio_det { get; set; }
    }
}

KermesseApp/Controllers/Tbl_productosController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KermesseApp.Models;
using Microsoft.Reporting.WebForms;

namespace KermesseApp.Controllers
{
    public class Tbl_productosController : Controller
    {
        KERMESSEEntities db = new KERMESSEEntities();

        //GET: Tbl_productos
        public ActionResult tbl_productos()
        {
            return View(db.tbl_productos.Where(model => model.estado != 3));
        }


        public ActionResult VwGuardarProd() //Invokes List View
        {
            ViewBag.id_comunidad = new SelectList(db.tbl_comunidad.Where(model => model.estado != 3), "id_comunidad", "nombre");
            ViewBag.id_cat_producto = new SelectList(db.tbl_cat_producto.Where(model => model.estado != 3), "id_cat_producto", "nombre");
            return View(); //Returns New Prod Cat View
        }

        [HttpPost]
        public ActionResult GuardarProducto(tbl_productos tp) //Method that saves new item
        {

            if (ModelState.IsValid)
            {
                tbl_productos tProd = new tbl_productos();
                tProd.id_comunidad = tp.id_comunidad;
                tProd.id_cat_producto = tp.id_cat_producto;
                tProd.nombre = tp.nombre;
                tProd.desc_presentacion = tp.desc_presentacion;
                tProd.cantidad = tp.cantidad;
                tProd.precio_venta = tp.precio_venta;
                tProd.estado = 1;


                db.tbl_productos.Add(tProd); //Add new item
                db.SaveChanges(); //Saves to model registry 
                ModelState.Clear();
                return RedirectToAction("tbl_Productos");
            }

            ViewBag.id_comunidad = new SelectList(db.tbl_comunidad.Where(model => model.estado != 3), "id_comunidad", "nombre");
            ViewBag.id_cat_producto = new SelectList(db.tbl_cat_producto.Where(model => model.estado != 3), "id_cat_producto", "nombre");
            return View("tbl_Productos");

        }

        public ActionResult EliminarProd(int id)
        {
            tbl_productos tp = new tbl_productos();
            tp = db.tbl_productos.Find(id);
            this.LogicalDeleteProducto(tp);

            return View("tbl_Productos");
        }

        [HttpPost]
        public ActionResult LogicalDeleteProducto(tbl_productos tp)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    tp.estado = 3;
                    db.Entry(tp).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("ListProductos");
            }
            catch (Exception)
            {
                return View();
                throw;
            }
        }
        public ActionResult VerProd(int id)
        {
            var Prod = db.tbl_productos.Where(x => x.id_producto == id).First();
            return View(Prod);
        }

        public ActionResult EditarProd(int? id)
        {
            tbl_productos tp = db.tbl_productos.Find(id);
            if (tp == null)
            {
                return HttpNotFound();
            }
            else
            {
                ViewBag.id_comunidad = new SelectList(db.tbl_comunidad, "id_comunidad", "nombre");
                ViewBag.id_cat_producto = new SelectList(db.tbl_cat_producto, "id_cat_producto", "nombre");
                return View(tp);
            }
        }

        [HttpPost]
        public ActionResult ActualizarProducto(tbl_productos tp)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    tp.estado = 2;
                    db.Entry(tp).State = EntityState.Modified;
                    db.SaveChanges();
                }
                ViewBag.id_comunidad = new SelectList(db.tbl_comunidad, "id_comunidad", "nombre");
                ViewBag.id_cat_producto = new SelectList(db.tbl_cat_producto, "id_cat_producto", "nombre");
                return RedirectToAction("tbl_Productos");
            }
            catch (Exception)
            {
                return View("tbl_Productos");
                throw;
            }
        }

        [HttpPost]

        public ActionResult FiltrarProd(String cadena)
        {
            if (String.IsNullOrEmpty(cadena))
            {
                var list = db.tbl_productos.ToList();
                return View("tbl_Productos", list);
            }
            else
            {
                var listaFiltrada = db.tbl_productos.Where(x => x.nombre.Contains(cadena) || x.desc_presentacion.Contains(cadena));
                return View("tbl_Productos", listaFiltrada);
            }
        }

        public ActionResult VerRptCatProd(String tipo, String cadena)
        {
            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;

            //cadena = formCollection.GetValue("cadena").AttemptedValue;

            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "rptProducto.rdlc");
            rpt.ReportPath = ruta;

            var listaFiltrada = from a in db.Producto() select a; //method to gather all db info

            if (!string.IsNullOrEmpty(cadena))
            {
                //List<tbl_productos> listaFiltrada = new List<tbl_productos>();
                listaFiltrada = listaFiltrada.Where(x => x.Producto.Contains(cadena) || x.Presentacion.Contains(cadena));
            }

            ReportDataSource rd = new ReportDataSource("dsProducto", listaFiltrada);
            rpt.DataSources.Add(rd);
            //tipo = "PDF";
            var b = rpt.Render(tipo, null, out mt, out enc, out f, out s, out w);
            return new FileContentResult(b, mt);
        }
    }
}

KermesseApp/Views/Tbl_productos/EditarProd.cshtml
@model KermesseApp.Models.tbl_productos

@{
    ViewBag.Title = "EditarProd";
}

@using (Html.BeginForm("ActualizarProducto", "Tbl_productos", FormMethod.Post))
{

    <style>
        .mydropdownlist {
            color: #3c3d3d;
            font-size: 14px;
            padding: 7px 12px;
            border: 1px solid #CED4DA;
            border-radius: 4px;
            background-color: #FFFFFF;
            width: 100%;
            height: 2.875rem;
            font-weight: 400;
            transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        }
    </style>

    <div class="col-12 grid-margin stretch-card">
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="https://as1.ftcdn.net/v2/jpg/00/41/40/38/1000_F_41403871_XgEFR2CYL5JdEPK47HcgaOTRduKImzV9.jpg" class="card-img-top" />
                </div>
                <div class="col-md-8">
                    <div class="card-body ">
                        <div class="card-title">
                            <h3 style="padding-top: 1rem;">Editar producto</h3>
                        </div>
                        <div class="card-description" style="padding-bottom: 1rem;">
                            Llene el siguiente formulario para editar este producto.
                        </div>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="row">
                            <div class="col">
                                <div class="form-group row">
                                    <div class="col-sm-9" style="margin-top:0.5rem;">
                                        <div><label>Comunidad</label></div>
                                        @Html.DropDownListFor(model => model.id_comunidad, null, htmlAttributes: new { @class = "mydropdownlist" })
                                        @Html.ValidationMessageFor(model => model.id_comunidad, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group row">
                                    <div class="col-sm-9" style="margin-top:0.5rem;">
                                        <div><label>Categoría</label></div>
                                        @Html.DropDownListFor(model => model.id_cat_producto, null, htmlAttributes: new { @class = "mydropdownlist" })
                                        @Html.ValidationMessageFor(model => model.id_cat_producto, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <div class="col-sm-9" style="margin-top:0.5rem;">
                                        <div><label>Nombre</label></div>
                                        @Html.TextBoxFor(x => x.nombre, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(x => x.nombre, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <div class="col-sm-9" style="margin-top:0.5rem;">
                                        <div><label>Descripción</label></div>
                                        @Html.TextAreaFor(x => x.desc_presentacion, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(x => x.desc_presentacion, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <div class="col-sm-9" style="padding-top:0.5rem;">
                                        <div><label>Cantidad</label></div>
                                        @Html.TextBoxFor(x => x.cantidad, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(x => x.cantidad, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <div class="col-sm-9" style="padding-top:0.5rem;">
                                        <div><label>Precio</label></div>
                                        @Html.TextBoxFor(x => x.precio_venta, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(x => x.precio_venta, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="padding-top:2rem;">
                            <div class="col">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-block btn-rounded btn-success">Guardar</button>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <button type="reset" class="btn btn-block btn-rounded btn-danger">Cancelar</button>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <a class="btn btn-rounded btn-block btn-inverse-info" href="@Url.Action("tbl_Productos")"> Regresar </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

KermesseApp/Views/Tbl_productos/VerProd.cshtml
@model KermesseApp.Models.tbl_productos

@{
    ViewBag.Title = "VerProd";
}

<div class="col-12 grid-margin stretch-card">
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="https://as1.ftcdn.net/v2/jpg/00/41/40/38/1000_F_41403871_XgEFR2CYL5JdEPK47HcgaOTRduKImzV9.jpg" class="card-img-top" />
            </div>
            <div class="col-md-8">
                <div class="card-body ">
                    <div class="card-title">
                        <h3 style="padding-top: 1rem;">Detalle del producto</h3>
                    </div>

                    <label class="card-description">Nombre</label>
                    <dd style="font-size:20px;">
                        @Html.DisplayFor(model => model.nombre)
                    </dd>

                    <label class="card-description">Descripción</label>
                    <dd style="font-size:20px;">
                        @Html.DisplayFor(model => model.desc_presentacion)
                    </dd>

                    <label class="card-description">Cantidad</label>
                    <dd style="font-size:20px;">
                        @Html.DisplayFor(model => model.cantidad)
                    </dd>

                    <label class="card-description">Precio</label>
                    <dd style="font-size:20px;">
                        @Html.DisplayFor(model => model.precio_venta)
                    </dd>

                    <label class="card-description">Categoría</label>
                    <dd style="font-size:20px;">
                        @Html.DisplayFor(model => model.tbl_cat_producto.nombre)
                    </dd>

                    <dt>
                        <label class="card-description">Comunidad</label>
                    </dt>
                    <dd style="font-size:20px;">
                        @Html.DisplayFor(model => model.tbl_comunidad.nombre)
                    </dd>
                    <div class="form-group" style="padding-top:2rem;">
                        <a class="btn btn-rounded btn-block btn-inverse-info" href="@Url.Action("Tbl_Productos")"> Regresar </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

KermesseApp/Views/Tbl_productos/VwGuardarProd.cshtml
@model KermesseApp.Models.tbl_productos

@{
    ViewBag.Title = "VwGuardarProd";
}

@using (Html.BeginForm("GuardarProducto", "Tbl_productos", FormMethod.Post))
{
    <style>
        .mydropdownlist {
            color: #3c3d3d;
            font-size: 14px;
            padding: 7px 12px;
            border: 1px solid #CED4DA;
            border-radius: 4px;
            background-color: #FFFFFF;
            width: 100%;
            height: 2.875rem;
            font-weight: 400;
            transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        }
    </style>

    @Html.AntiForgeryToken()

    <div class="col-12 grid-margin stretch-card">
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="https://as1.ftcdn.net/v2/jpg/00/41/40/38/1000_F_41403871_XgEFR2CYL5JdEPK47HcgaOTRduKImzV9.jpg" class="card-img-top" />
                </div>
                <div class="col-md-8">
                    <div class="card-body ">
                        <div class="card-title">
                            <h3 style="padding-top: 1rem;">Nuevo producto</h3>
                        </div>
                        <div class="card-description" style="padding-bottom: 1rem;">
                            Llene el siguiente formulario para guardar un producto.
                        </div>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="row">
                            <div class="col">
                                <div class="formgroup row">
                                    <div class="col-sm-9" style="margin-top:0.5rem;">
                                        <div><label>Comunidad</label></div>
                                        @Html.DropDownListFor(model => model.id_comunidad, ViewBag.id_comunidad as SelectList, "Seleccione...", new { @class = "mydropdownlist" })
                                        @Html.ValidationMessageFor(model => model.id_comunidad, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group row">
                                    <div class="col-sm-9" style="margin-top:0.5rem;">
                                        <div><label>Categoría</label></div>
                                        @Html.DropDownListFor(model => model.id_cat_producto, ViewBag.id_cat_producto as SelectList, "Seleccione...", htmlAttributes: new { @class = "mydropdownlist" })
                                        @Html.ValidationMessageFor(model => model.id_cat_producto, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <div class="col-sm-9" style="margin-top:0.5rem;">
                                        <div><label>Nombre</label></div>
                                        @Html.TextBoxFor(x => x.nombre, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <div class="col-sm-9" style="margin-top:0.5rem;">
                                        <div><label>Descripción</label></div>
                                        @Html.TextAreaFor(x => x.desc_presentacion, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.desc_presentacion, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <div class="col-sm-9" style="padding-top:0.5rem;">
                                        <div><label>Cantidad</label></div>
                                        @Html.TextBoxFor(x => x.cantidad, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.cantidad, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <div class="col-sm-9" style="padding-top:0.5rem;">
                                        <div><label>Precio</label></div>
                                        @Html.TextBoxFor(x => x.precio_venta, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.precio_venta, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="padding-top:2rem;">
                            <div class="col">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-block btn-rounded btn-success">Guardar</button>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <button type="reset" class="btn btn-block btn-rounded btn-danger">Cancelar</button>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <a class="btn btn-rounded btn-block btn-inverse-info" href="@Url.Action("tbl_Productos")"> Regresar </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

KermesseApp/Views/Tbl_productos/tbl_Productos.cshtml
@model IEnumerable<KermesseApp.Models.tbl_productos>

@{
    ViewBag.Title = "tbl_Productos";
}

@using (Html.BeginForm("FiltrarProd", "Tbl_productos", FormMethod.Post))
{
    <h2 style="padding-bottom: 2rem;">Productos</h2>

    <div class="row justify-content-end" style="padding-bottom: 2rem;">
        <div class="col-md-auto" style="padding-right:8rem;">
            <p>
                <a href="@Url.Action("VwGuardarProd")"
                   class="btn btn-rounded btn-primary">
                    <ion-icon name="add-outline"></ion-icon>
                    <span>
                        <strong>Añadir Nuevo</strong>
                    </span>
                </a>
            </p>
        </div>
        <div class="col-sm-6" style="padding-right: 1.5rem;">
            <div class="input-group">
                @Html.TextBox("cadena", null, new { @class = "form-control col-sm-10", @placeholder = "Buscar", @name = "search-outline" })
                <div class="input-group-append">
                    <button type="submit" class="btn btn-rounded btn-success">
                        <ion-icon name="search" style="pointer-events:none;"></ion-icon> Buscar
                    </button>
                </div>
            </div>
        </div>
        <div class="col px-0">
            @Html.ActionLink("PDF", "VerRptCatProd", new { tipo = "PDF", cadena = Request.Form["cadena"] }, new { @class = "btn btn-rounded btn-inverse-info" })
            @Html.ActionLink("Word", "VerRptCatProd", new { tipo = "Word", cadena = Request.Form["cadena"] }, new { @class = "btn btn-rounded btn-inverse-info" })
            @Html.ActionLink("Excel", "VerRptCatProd", new { tipo = "Excel", cadena = Request.Form["cadena"] }, new { @class = "btn btn-rounded btn-inverse-info" })
        </div>
    </div>

    <div class=" table table-hover table-responsive-xl">
        <table class="table table-hover">
            <thead style="background-color: #e6eaf1;">
                <tr>
                    <th>
                        @Html.Label("Nombre")
                    </th>
                    <th>
                        @Html.Label("Descripción")
                    </th>
                    <th>
                        @Html.Label("Cantidad")
                    </th>
                    <th>
                        @Html.Label("Precio")
                    </th>
                    <th>
                        @Html.Label("Categoría")
                    </th>
                    <th>
                        @Html.Label("Comunidad")
                    </th>
                    <th class="text-center">
                        @Html.Label("Acciones")
                    </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-wrap" style="width: 5rem;">
                            @Html.DisplayFor(modelItem => item.nombre)
                        </td>
                        <td class="text-wrap" style="max-width: 30rem;">
                            @Html.DisplayFor(modelItem => item.desc_presentacion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.cantidad)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.precio_venta)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tbl_cat_producto.nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tbl_comunidad.nombre)
                        </td>
                        <td>
                            <a class="btn btn-rounded btn-sm btn-warning" href="@Url.Action("EditarProd", new { id = item.id_producto })"><ion-icon name="create-outline" style="pointer-events:none;"></ion-icon> Editar </a>
                            <a class="btn btn-rounded btn-sm btn-success" href="@Url.Action("VerProd", new { id = item.id_producto })"><ion-icon name="document-text-outline" pointer-events: none;"></ion-icon> Detalle</a>
                            <a class="btn btn-rounded btn-sm btn-danger" href="@Url.Action("EliminarProd", new { id = item.id_producto })"><ion-icon name="trash-outline" style="pointer-events: none;"></ion-icon> Eliminar </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}